#valid
GET http://localhost:80/user/token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsImV4cCI6MTY2OTg2Njk1OH0.f5QwtdSv8ECvnFBx5yFT-8YSQr1b7nGj1eZZ59zBpIY
#Accept: application/json

###

#invalid
GET http://localhost:80/user/token?token=something
#Accept: application/json

###