server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://root:iamroot@resource.delimiter@@mongo.server.address@:27017/
      database: etms
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 64MB

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.discriptor.sql.BasicBinder: trace

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
