server:
  port: 8082

spring:
  datasource:
    username: root
    password: HCC.mysql.pw#0
    url: jdbc:mysql://@mysql.server.address@:3306/exp_sys
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.discriptor.sql.BasicBinder: trace

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
