server:
  port: 8081
  servlet:
    context-path: /course

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://120.78.65.145:3306/course_sys
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.discriptor.sql.BasicBinder: trace

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
